### ISSUE TITLE
Should we remove `N` from the ruff config?

### ISSUE THREAD

**Issue by Cadair** [sunpy/package-template#145]
### Provide a general description of the issue or problem.

From rolling out this config to a few repos it seems that's it's pretty common for us to use mixed case to express a more technical or scientific variable name, i.e. `Tx` or `MeV` etc. I wonder if it's actually worth having in the config at all?

@CyclingNinja @nabobalis

**Comment by nabobalis** [comment]
Yeah, its a problem with actual SI units, how often does it happen?

The other choice is to ignore certain lines but that might just get really noisy/ugly in the long term.

**Comment by Cadair** [comment]
> Yeah, its a problem with actual SI units, how often does it happen?

It happened many in both sunkit-spex and core. It also happened a bunch in ndcube but mainly for `xD` i.e. `plot_2D`.

**Comment by nabobalis** [comment]
Disable it then.
