### ISSUE TITLE
Automate retemplating and template updates

### ISSUE THREAD

**Issue by wtbarnes** [sunpy/package-template#19]
As the number of packages in the sunpy ecosystem, both affiliated and sponsored, grows, the burden of maintaining the infrastructure behind all of these packages grows. This is mainly relevant to propagating changes in the package template downstream to those packages that use it. Rather than placing the burden of doing this on the maintainers of the template or the project maintainers, it would be nice to automate this in some way. For example, every time the package template is updated or "released," a bot could open a PR on every sponsored package updating the relevant bits.

See also sunpy/sunpy-project#2
See also https://github.com/sunpy/package-template/issues/3

There are probably more bits here that I'm missing.

**Comment by Cadair** [comment]
This is in theory closed by OpenAstronomy/packaging-guide#45 but we haven't actually tested it in the wild yet.
