### ISSUE TITLE
Small misconfigurations in setup.cfg and project.toml 

### ISSUE THREAD

**Issue by samaloney** [sunpy/package-template#20]
### Description

Clean package using template
1. setup.cfg doesn't have `include_package_data = True` so the 'MANIFEST.in' file is ignored
2. Towncrier config seems to use the project name ('MyProject') rather than default generate package name ('myproject') so can't find the what's new. 

### Expected vs Actual behavior

1. Maybe either don't include the manifest file or `include_package_data = True` in setup.cfg 
2. Update the template to use the package not project name?

### System Details

- SunPy Version:
- Astropy Version:
- Python Version:
- OS information:

**Comment by nabobalis** [comment]
1. This is fixed upstream by https://github.com/OpenAstronomy/packaging-guide/pull/13, hopefully when that is merged, we can merge it here.

2. Is fixed by https://github.com/sunpy/package-template/pull/21
