### ISSUE TITLE
Indentation in the CI yaml is wrong

### ISSUE THREAD

**Issue by Cadair** [sunpy/package-template#56]
### Describe the bug

I fixed it here: https://github.com/sunpy/sunkit-magex/commit/3afdf3b06b83b597faa635e36d0570d4768e2d6e

### To Reproduce

import sunpy

sunpy.map.Map(...)
etc

**Comment by samaloney** [comment]
I don't think pytest-xdist or what ever that package is installed by default either so the `posargs` with `-n auto` will cause the tests to fail on the CI. Not sure if you want to add the required dep the tests section of remove the `posargs` from the actions yaml?
