### ISSUE TITLE
Include norecursedirs option with {package}/_dev to pytest config

### ISSUE THREAD

**Issue by samaloney** [sunpy/package-template#70]
### Describe the bug

Running the test crashes as setuptools_scm isn't installed so similar to sunpy add `norecursedirs = ['{package}/_dev']` to the pytest options

### To Reproduce

```
pytest -vvv -r fEs --pyargs <packagename> --cov-report=xml --cov=<packagename> --cov-config=pyproject.toml docs --cov-report=xml:coverage.xml -n auto```

**Comment by nabobalis** [comment]
This seems to be fixed by those commit references.
