### ISSUE TITLE
Should we add a circleci only mode?

### ISSUE THREAD

**Issue by Cadair** [sunpy/package-template#8]
@ehsteve pointed out during the community meeting that setting up or migrating CI is a bit of a faff. 

Rather than adding another CI service like GitHub actions or travis, one easy thing we could do is add a circleci only mode which runs the tox test and code style envs on circleci. This would mean you only have to setup the one env and get your tests run.

The downside is obviously that you only get linux builds.

**Comment by nabobalis** [comment]
With the switch to Azure, I think it might be worth just deleting CircleCI config as a base and if people need it for their own package, they can set it up.

**Comment by CyclingNinja** [comment]
Closing this issue as no longer relevant, all deployments appear to be handled by GitHub actions

**Comment by Cadair** [comment]
We do still use circle ci for figure test builds, but yes this issue can go.
